#!/bin/bash

zig build-obj --strip --release-small -target avr-freestanding-none -mcpu=atmega328p ${ARDUINO_ZIG_PROJECT_ROOT}/src/main.zig
#zig build-obj -femit-asm -fno-emit-bin --strip --release-small -target avr-freestanding-none -mcpu=atmega328p ${ARDUINO_ZIG_PROJECT_ROOT}/src/main.zig

if [ ! -d "${ARDUINO_ZIG_PROJECT_ROOT}/build" ]; then
    mkdir build
fi

mv main.o ${ARDUINO_ZIG_PROJECT_ROOT}/build
cd ${ARDUINO_ZIG_PROJECT_ROOT}/build
avr-ld -o main.elf main.o
avr-objcopy -j .text -j .data -O ihex main.elf main.hex

cd -
